import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import {
  LayoutDashboard,
  CalendarCheck,
  ListTodo,
  Settings,
} from "lucide-react";
import Sidebar, { SidebarItem } from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex">
          <Sidebar>
            <SidebarItem
              icon={<LayoutDashboard size={20} />}
              text={"Home"}
              path="/"
            />
            <SidebarItem
              icon={<CalendarCheck size={20} />}
              text={"Schedule"}
              path="/schedule"
            />
            <SidebarItem
              icon={<ListTodo size={20} />}
              text={"Task"}
              path="/task"
            />
            <SidebarItem
              icon={<Settings size={20} />}
              text={"Setting"}
              path="/setting"
            />
            <SidebarItem
              icon={<Settings size={20} />}
              text={"Category"}
              path="/category"
            />
          </Sidebar>
          <div className="w-screen h-screen">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
