@dev_url=http://localhost:8080/api/v1/

# Get all category
POST {{dev_url}}/categories
Content-Type: application/json

{
    "user": "655a1d62787fe99d2289b2f7"
}

###

# Create new category
POST {{dev_url}}/categories/create
content-type: application/json

{
    "name": "HUST",
    "color": "red",
    "description": "my school",
    "user": "655a1d62787fe99d2289b2f7"
}

###

# Get detail a category
GET {{dev_url}}/categories/655870d01094d1c106c73105

###

# Update a category
PUT {{dev_url}}/categories/655870d01094d1c106c73105
content-type: application/json

{
    "name": "HUST 2",
    "color": "red",
    "description": "my school",
    "user": "655a1d62787fe99d2289b2f7"
}

###

# Delete a category
DELETE {{dev_url}}/categories/655870d01094d1c106c73105