@dev_url=http://localhost:8080/api/v1/

# Get all tasks by user id 
POST {{dev_url}}/tasks
content-type: application/json

{
    "user": "655a1d62787fe99d2289b2f7"
}

###

# Create new task
POST {{dev_url}}/tasks/create
content-type: application/json

{
    "name": "New task 3",
    "start_day": "2023-12-01T15:13:23.863Z",
    "end_day": "2023-12-02T10:20:18.378Z",
    "color": "red",
    "description": "This is a new task 3",
    "user": "655a1d62787fe99d2289b2f7",
    "category": "655a1d63787fe99d2289b303",
    "status": 1,
    "priority": 3
}

###

# Get detail one task
GET {{dev_url}}/tasks/655b597e0bd8a5771617cc8f

###

# Update a task
PUT {{dev_url}}/tasks/655b597e0bd8a5771617cc8f
content-type: application/json

{
    "name": "New task 4",
    "start_day": "2024-03-01T15:13:23.863Z",
    "end_day": "2023-12-02T10:20:18.378Z",
    "color": "red",
    "description": "This is a new task 4",
    "user": "655a1d62787fe99d2289b2f7",
    "category": "655a1d63787fe99d2289b303",
    "status": 1,
    "priority": 3
}

###

# Delete a task
DELETE {{dev_url}}/tasks/655b193ac486fae187942315

# Search by day
GET {{dev_url}}/tasks/search/2023-11-27/2023-11-27